[project]
name = "test-trait-callback"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]


[contracts.my-contract-2]
path = "contracts/my-contract-2.clar"
depends_on = ["my-contract", "callback-trait"]

[contracts.my-contract]
path = "contracts/my-contract.clar"
depends_on = []

[contracts.callback-trait]
path = "contracts/callback-trait.clar"
depends_on = ["callback-trait"]


[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
